name: Make TWRP Device (Android 15 Optimized)

on:
  workflow_dispatch:
    inputs:
      IMGURL:
        description: 'URL of initboot.img (Android 15 REQUIRED)'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r25b" >> $GITHUB_ENV

      - name: Build Magiskboot from Source
        run: |
          git clone --depth=1 https://github.com/topjohnwu/Magisk.git
          cd Magisk
          export ANDROID_NDK_HOME=$HOME/android-ndk-r25b
          ./build.py native  # 修复：使用 native 参数

      - name: Copy Magiskboot Binary
        run: |
          cp Magisk/native/out/magiskboot .  # 复制编译好的二进制文件
          chmod +x magiskboot

      - name: Download initboot.img
        run: |
          wget -O initboot.img "${{ github.event.inputs.IMGURL }}"

      - name: Extract Ramdisk
        run: |
          ./magiskboot unpack initboot.img
          mkdir ramdisk
          cd ramdisk
          cpio -idv < ../ramdisk.cpio

      - name: Create DeviceTree
        run: |
          # 创建设备树文件
          mkdir -p device_tree
          cd ramdisk
          find . -type f -name "*.fstab*" -exec cp --parents {} ../device_tree \;
          find . -type f -name "*.rc" -exec cp --parents {} ../device_tree \;
          cp -r fstab* ../device_tree/ 2>/dev/null || true
          cp -r etc ../device_tree/ 2>/dev/null || true

      - name: Create DeviceTree ZIP
        run: |
          cd device_tree
          zip -r ../DeviceTree.zip .
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DeviceTree
          path: DeviceTree.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android15-${{ github.run_id }}
          body: |
            Auto-generated TWRP device tree for Android 15
            Source: ${{ github.event.inputs.IMGURL }}
            Magiskboot: Compiled from source
            Build date: $(date "+%Y-%m-%d %H:%M:%S")
          files: DeviceTree.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
