name: Make TWRP Device (Android 15 Optimized)

on:
  workflow_dispatch:
    inputs:
      IMGURL:
        description: 'URL of initboot.img (Android 15 REQUIRED)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download initboot.img
      run: |
        curl -L -o initboot.img "${{ github.event.inputs.IMGURL }}"
        echo "Downloaded initboot.img:"
        file initboot.img

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget unzip python3 python3-pip cpio
        pip3 install requests

    - name: Clone Magisk
      run: |
        git clone --recurse-submodules https://github.com/topjohnwu/Magisk.git
        cd Magisk
        git checkout $(git describe --tags `git rev-list --tags --max-count=1`)

    - name: Setup NDK using Magisk build script
      run: |
        cd Magisk
        python3 build.py ndk

    - name: Build magiskboot
      run: |
        cd Magisk
        export ANDROID_NDK_HOME="$(pwd)/ndk"
        export PATH="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
        python3 build.py magiskboot
        cp ./app/src/main/jni/magiskboot/magiskboot ../magiskboot

    - name: Extract ramdisk
      run: |
        chmod +x magiskboot
        ./magiskboot unpack initboot.img
        ls -la

    - name: Extract device tree
      run: |
        if [ -f ramdisk.cpio ]; then
          echo "Found ramdisk.cpio"
          mkdir ramdisk
          cd ramdisk
          cpio -i < ../ramdisk.cpio
          find . -name "*.dtb" -exec cp {} ../device_tree.dtb \;
          cd ..
        elif [ -f boot.img ]; then
          echo "Found boot.img"
          mkdir ramdisk
          cd ramdisk
          cpio -i < ../boot.img
          find . -name "*.dtb" -exec cp {} ../device_tree.dtb \;
          cd ..
        else
          echo "No ramdisk found, checking for DTB in initboot.img"
          ./magiskboot dtb initboot.img dtb.img
          if [ -f dtb.img ]; then
            cp dtb.img device_tree.dtb
          else
            echo "ERROR: No device tree found"
            exit 1
          fi
        fi

    - name: Verify device tree
      run: |
        if [ -f device_tree.dtb ]; then
          file device_tree.dtb
          dtc -I dtb -O dts device_tree.dtb | head -20
        else
          echo "ERROR: device_tree.dtb not found"
          exit 1
        fi

    - name: Repack initboot
      run: |
        ./magiskboot repack initboot.img new_initboot.img
        file new_initboot.img

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: twp-device-files
        path: |
          device_tree.dtb
          new_initboot.img
        retention-days: 30

    - name: Generate build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Source URL**: ${{ github.event.inputs.IMGURL }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Device Tree**: $(file device_tree.dtb)" >> $GITHUB_STEP_SUMMARY
        echo "- **Repacked Image**: $(file new_initboot.img)" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Date**: $(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_STEP_SUMMARY
