name: Make TWRP Device (Android 15 Optimized)

on:
  workflow_dispatch:
    inputs:
      IMGURL:
        description: 'URL of initboot.img (Android 15 REQUIRED)'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install -y git wget unzip python3 python3-pip openjdk-17-jdk
        pip3 install pyyaml requests

    - name: Clone Magisk
      run: git clone https://github.com/topjohnwu/Magisk.git

    - name: Cache NDK
      id: cache-ndk
      uses: actions/cache@v4
      with:
        path: |
          Magisk/android-ndk-r25b
          ~/.cache/ndk
        key: ndk-r25b-${{ runner.os }}-${{ hashFiles('Magisk/build.py') }}
        restore-keys: |
          ndk-r25b-${{ runner.os }}-
          ndk-r25b-

    - name: Install NDK
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      working-directory: Magisk
      run: ./build.py ndk

    - name: Set Environment Variables
      run: |
        echo "ANDROID_NDK_HOME=$PWD/Magisk/android-ndk-r25b" >> $GITHUB_ENV
        echo "NDK=$PWD/Magisk/android-ndk-r25b" >> $GITHUB_ENV

    - name: Build Magiskboot
      working-directory: Magisk
      run: ./build.py native

    - name: Download Boot Image
      run: wget -O initboot.img "${{ github.event.inputs.IMGURL }}"

    - name: Unpack Boot Image
      run: |
        mkdir boot
        cd boot
        ../Magisk/magiskboot unpack ../initboot.img

    - name: Create Device Tree
      run: |
        mkdir -p device/twrp
        cd device/twrp
        cp ../../boot/init_boot.img init_boot.img
        echo '# TWRP Device Tree' > README.md
        echo 'Source: ${{ github.event.inputs.IMGURL }}' >> README.md
        echo 'Build date: $(date "+%Y-%m-%d %H:%M:%S")' >> README.md

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-device-tree
        path: device/
        retention-days: 30
