name: Make TWRP Device (Android 15 Optimized)

on:
  workflow_dispatch:
    inputs:
      IMGURL:
        description: 'URL of initboot.img (Android 15 REQUIRED)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download initboot.img
      run: |
        curl -L -o initboot.img "${{ github.event.inputs.IMGURL }}"
        echo "Downloaded initboot.img:"
        file initboot.img

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget unzip python3 cpio
        pip3 install requests

    - name: Clone Magisk
      run: |
        git clone https://github.com/topjohnwu/Magisk.git
        cd Magisk
        git submodule update --init --recursive

    - name: Install NDK
      working-directory: Magisk
      run: python3 build.py ndk

    - name: Build Magisk binaries
      working-directory: Magisk
      run: python3 build.py native

    - name: Copy magiskboot
      run: |
        cp Magisk/native/out/magiskboot .
        chmod +x magiskboot
        echo "magiskboot copied successfully"
        file magiskboot

    - name: Extract device tree
      run: |
        echo "Extracting device tree from initboot.img"
        ./magiskboot unpack initboot.img
        if [ -f ramdisk.cpio ]; then
          echo "Found ramdisk.cpio, extracting..."
          mkdir ramdisk
          cd ramdisk
          cpio -i < ../ramdisk.cpio
          if [ -f dtb ]; then
            cp dtb ../devicetree.dtb
            echo "Device tree extracted to devicetree.dtb"
          else
            echo "DTB not found in ramdisk"
            exit 1
          fi
          cd ..
        else
          echo "ramdisk.cpio not found, trying direct DTB extraction"
          ./magiskboot dtb initboot.img > devicetree.dtb
          if [ -s devicetree.dtb ]; then
            echo "Device tree extracted directly to devicetree.dtb"
          else
            echo "Failed to extract device tree"
            exit 1
          fi
        fi

    - name: Repack initboot.img
      run: |
        echo "Repacking initboot.img with extracted device tree"
        ./magiskboot repack initboot.img newinitboot.img
        echo "Repacked image created: newinitboot.img"
        file newinitboot.img

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: twrp-device-files
        path: |
          devicetree.dtb
          newinitboot.img
        retention-days: 30

    - name: Generate build report
      run: |
        echo "## Build Report" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Date**: $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        echo "- **Device Tree**: $(file devicetree.dtb)" >> $GITHUB_STEP_SUMMARY
        echo "- **Repacked Image**: $(file newinitboot.img)" >> $GITHUB_STEP_SUMMARY
        echo "- **Magiskboot Version**: $(./magiskboot -v)" >> $GITHUB_STEP_SUMMARY
