name: Make TWRP Device (Android 15 Optimized)

on:
  workflow_dispatch:
    inputs:
      IMGURL:
        description: 'URL of initboot.img (Android 15 REQUIRED)'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30  # 添加超时控制
    
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        
      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y git wget unzip python3-pip
          pip3 install twrpdtgen
          
      - name: Download NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV
          
      - name: Cache NDK  # 添加缓存加速
        uses: actions/cache@v4
        with:
          path: android-ndk-r25b
          key: ndk-r25b-${{ runner.os }}
          
      - name: Build Magiskboot from Source
        run: |
          git clone https://github.com/topjohnwu/Magisk.git
          cd Magisk
          ./build.py native  # 修复：使用native参数而不是magiskboot
          cp native/out/magiskboot ../
          chmod +x ../magiskboot
          
      - name: Download and Extract initboot.img
        run: |
          wget ${{ github.event.inputs.IMGURL }} -O initboot.img
          ./magiskboot unpack initboot.img
          
      - name: Generate TWRP Device Tree
        run: |
          mkdir -p twrp-device-tree
          twrpdtgen initboot.img -o twrp-device-tree
          find twrp-device-tree -name fstab.* -exec cp {} . \;
          find twrp-device-tree -name init.*.rc -exec cp --parents {} twrp-device-tree \;
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: android15-${{ github.run_id }}
          files: |
            twrp-device-tree.tar.gz
            magiskboot
          body: |
            Auto-generated TWRP device tree for Android 15
            Source: ${{ github.event.inputs.IMGURL }}
            Magiskboot: Compiled from source
            Build date: $(date "+%Y-%m-%d %H:%M:%S")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload TWRP Device Tree  # 修复：升级到v4
        uses: actions/upload-artifact@v4
        with:
          name: twrp-device-tree
          path: twrp-device-tree.tar.gz
          retention-days: 30  # 添加保留期限
          
      - name: Upload Magiskboot Binary  # 新增：上传magiskboot
        uses: actions/upload-artifact@v4
        with:
          name: magiskboot-binary
          path: magiskboot
          retention-days: 30
          
      - name: Check Disk Space  # 新增：健康检查
        run: df -h
